server:
  port: 8083
  servlet:
    context-path: /eshop


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 260698


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true